service: sam-serverless

custom:
  usersTable: Users
  accessesTable: Accesses

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, "ap-northeast-1"}
  profile: ${opt:profile, "default"}
  stage: ${opt:stage, "dev"}
  apiStage: ${opt:apiStage, "master"}
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  versionFunctions: false # optional, default is true
  environment:
    USERS_TABLE: ${self:custom.usersTable}
    ACCESSES_TABLE: ${self:custom.accessesTable}
    REGION: ${self:provider.region}
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"

functions:
  PutUser:
    handler: handler.putUser
    name: sam-server-putUser-${self:provider.stage}

  GetUserStatus:
    handler: handler.getUserStatus
    name: sam-server-getUserStatus-${self:provider.stage}

  PutUserEntry:
    handler: handler.putUserEntry
    name: sam-server-putUserEntry-${self:provider.stage}

  PutUserExit:
    handler: handler.putUserExit
    name: sam-server-putUserExit-${self:provider.stage}

  GetUsers:
    handler: handler.getUsers
    name: sam-server-getUsers-${self:provider.stage}

# you can add CloudFormation resource templates here
resources:
  - ${file(./resources/SamserverlessApi.yml)}
  - ${file(./resources/SamServerlessApiDeployment.yml)}
  - ${file(./resources/PutUserPermission.yml)}
  - ${file(./resources/GetUserStatusPermission.yml)}
  - ${file(./resources/PutUserEntryPermission.yml)}
  - ${file(./resources/PutUserExitPermission.yml)}
  - ${file(./resources/GetUsersPermission.yml)}
  - ${file(./resources/UsersTable.yml)}
  - ${file(./resources/AccessesTable.yml)}

package:
  exclude:
    - resources/**
