service: sam-serverless

custom:
  usersTable: Users
  accessesTable: Accesses

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, "ap-northeast-1"}
  profile: ${opt:profile, "default"}
  stage: ${opt:stage, "dev"}
  apiStage: ${opt:apiStage, "master"}
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  versionFunctions: false # optional, default is true
  environment:
    USERS_TABLE: ${self:custom.usersTable}
    ACCESSES_TABLE: ${self:custom.accessesTable}
    REGION: ${self:provider.region}
    TZ: Asia/Tokyo
    FROM_MAIL_ADDRESS: ${opt:fromMailAddress, ""}
    TO_MAIL_ADDRESS: ${opt:toMailAddress, ""}
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"

functions:
  PutUser:
    handler: handler.putUser
    name: sam-server-putUser-${self:provider.stage}

  GetUserStatus:
    handler: handler.getUserStatus
    name: sam-server-getUserStatus-${self:provider.stage}

  PutUserEntry:
    handler: handler.putUserEntry
    name: sam-server-putUserEntry-${self:provider.stage}

  PutUserExit:
    handler: handler.putUserExit
    name: sam-server-putUserExit-${self:provider.stage}

  GetUsers:
    handler: handler.getUsers
    name: sam-server-getUsers-${self:provider.stage}

  ExecuteExitProcessAll:
    handler: handler.executeExitProcessAll
    name: sam-server-stepFunction-executeExitProcessAll-${self:provider.stage}

  GetAccessesOfTody:
    handler: handler.getAccessesOfTody
    name: sam-server-stepFunction-getAccessesOfTody-${self:provider.stage}

  SendMail:
    handler: handler.sendMail
    name: sam-server-stepFunction-sendMail-${self:provider.stage}

# you can add CloudFormation resource templates here
resources:
  - ${file(./resources/ApiGateway.yml)}
  - ${file(./resources/LambdaPermissions.yml)}
  - ${file(./resources/Tables.yml)}

package:
  exclude:
    - resources/**
    - myLayer/**