Resources:
  AccessesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Accesses
      AttributeDefinitions:
        -
          AttributeName: userId
          AttributeType: S
        -
          AttributeName: date
          AttributeType: S
      KeySchema:
        -
          AttributeName: userId
          KeyType: HASH
        -
          AttributeName: date
          KeyType: RANGE
      GlobalSecondaryIndexes:
        -
          IndexName: date-index
          KeySchema:
            -
              AttributeName: date
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
