Resources:
  SamServerlessApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: sam-serverless-restApi-${self:provider.stage}
      Body: ${file(./resources/swagger.yml)}
    DependsOn:
     - PutUserLambdaFunction
     - GetUserStatusLambdaFunction
     - PutUserEntryLambdaFunction
     - PutUserExitLambdaFunction
     - GetUsersLambdaFunction

  SamServerlessApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref SamServerlessApi
      StageName: ${self:provider.apiStage}
    DependsOn: SamServerlessApi