Resources:
  GetUsersPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: sam-server-getUsers-${self:provider.stage}
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:"
            - !Ref AWS::Region
            - ":"
            - !Ref AWS::AccountId
            - ":"
            - !Ref SamServerlessApi
            - /${self:provider.apiStage}/GET/users
    DependsOn: SamServerlessApiDeployment