Resources:
  GetUserStatusPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: sam-server-getUserStatus-${self:provider.stage}
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:"
            - !Ref AWS::Region
            - ":"
            - !Ref AWS::AccountId
            - ":"
            - !Ref SamServerlessApi
            - /${self:provider.apiStage}/GET/user/{cardId}
    DependsOn: SamServerlessApiDeployment
