Resources:
  GetUsersPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: sam-server-getUsers-${self:provider.stage}
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:"
            - !Ref AWS::Region
            - ":"
            - !Ref AWS::AccountId
            - ":"
            - !Ref SamServerlessApi
            - /${self:provider.apiStage}/GET/users
    DependsOn: SamServerlessApiDeployment

  GetUserStatusPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: sam-server-getUserStatus-${self:provider.stage}
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:"
            - !Ref AWS::Region
            - ":"
            - !Ref AWS::AccountId
            - ":"
            - !Ref SamServerlessApi
            - /${self:provider.apiStage}/GET/user/{cardId}
    DependsOn: SamServerlessApiDeployment

  PutUserEntryPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: sam-server-putUserEntry-${self:provider.stage}
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:"
            - !Ref AWS::Region
            - ":"
            - !Ref AWS::AccountId
            - ":"
            - !Ref SamServerlessApi
            - /${self:provider.apiStage}/PUT/user/{cardId}/entry
    DependsOn: SamServerlessApiDeployment

  PutUserExitPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: sam-server-putUserExit-${self:provider.stage}
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:"
            - !Ref AWS::Region
            - ":"
            - !Ref AWS::AccountId
            - ":"
            - !Ref SamServerlessApi
            - /${self:provider.apiStage}/PUT/user/{cardId}/exit
    DependsOn: SamServerlessApiDeployment

  PutUserPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: sam-server-putUser-${self:provider.stage}
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:"
            - !Ref AWS::Region
            - ":"
            - !Ref AWS::AccountId
            - ":"
            - !Ref SamServerlessApi
            - /${self:provider.apiStage}/PUT/user
    DependsOn: SamServerlessApiDeployment
