swagger: '2.0'
info:
  title: sta access manager
  description: 入退室管理アプリAPI
  version: 0.0.0
  termsOfService: 'https://github.com/ikkyu-3/sta_access_manager'
host: hostname
schemes:
  - https
basePath: /
tags:
  - name: User
    description: サービス利用者
paths:
  /user:
    put:
      summary: ユーザー登録・更新
      description: |
        ユーザを登録・更新することができる
      parameters:
        - in: body
          name: user
          description: idで指定したユーザの登録情報を更新。
          schema:
            type: object
            required:
              - id
              - name
              - carId
            properties:
              id:
                type: string
              name:
                type: string
              cardId:
                type: string
      tags:
        - User
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        '400':
          description: bad request
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
  /user/{cardId}/status:
    get:
      summary: ユーザの入退室状況を取得
      description: 指定したカードIDに紐づくユーザの、本日の入退室状況を取得する
      parameters:
        - in: path
          required: true
          name: cardId
          type: string
      tags:
        - User
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              user:
                type: object
                properties:
                  userId:
                    type: string
                  name:
                    type: string
                  purpose:
                    type: string
                  isEntry:
                    type: boolean
                  entryTime:
                    type: string
                  exitTime:
                    type: string
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Not Found
          schema:
            type: object
            properties:
              message:
                type: string
              exists:
                type: boolean
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: 入退室リクエスト
      description: |
        入室処理
        - Accessesに項目を追加
        - 再入室の場合は該当する項目のrecordsリストに入室情報を新規追加

        退室処理
        - 該当する項目のrecordsリストのに退室情報を追加
      parameters:
        - in: path
          required: true
          name: cardId
          type: string
        - in: body
          required: false
          name: purpose
          description: 入室目的
          schema:
            type: object
            required:
              - purpose
            properties:
              purpose:
                type: string
      tags:
        - User
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              message:
                type: string
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Not Found
          schema:
            type: object
            properties:
              message:
                type: string
              exists:
                type: boolean
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
  /users:
    get:
      summary: 参加者一覧
      tags:
        - User
      responses:
        '200':
          description: |
            OK

            並び順 ... entiryTime順(昇順)
          schema:
            type: array
            items:
              type: object
              properties:
                userId:
                  type: string
                name:
                  type: string
                purpose:
                  type: string
                isEntry:
                  type: boolean
                entryTime:
                  type: string
                  format: date-time
                exitTime:
                  type: string
                  format: date-time
        '400':
          description: bad request
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: bad request
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    type: object
    properties:
      message:
        type: string
